tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "clojure/tools"

# Libraries
brew "gmp"
brew "libyaml"
brew "openssl@1.1"
brew "openssl@3"
brew "readline"
brew "wxmac"

# Binaries
cask "1password"
cask "1password-cli"
cask "session-manager-plugin"
brew "argocd"
brew "autoconf"
brew "awscli"
brew "aws-iam-authenticator"
brew "cmake"
brew "chisel"
brew "clojure"
brew "colima"
brew "comby"
brew "coreutils"
brew "fswatch"
brew "fzf"
brew "gawk"
brew "gh"
brew "git"
brew "hugo"
brew "ijq"
brew "jq"
brew "k3d"
brew "kubectl"
brew "kubectx"
brew "kube-ps1"
brew "lua"
brew "luajit"
brew "neovim"
brew "nim"
brew "opam"
brew "ripgrep"
brew "tilt"
brew "tree"
brew "watch"
brew "yj"
brew "zig"

# Apps
cask "google-chrome"
cask "docker"
cask "google-cloud-sdk"
cask "gpg-suite-no-mail"
cask "hiddenbar"
cask "iterm2"
cask "obsidian"
cask "rectangle"
cask "zoom"

# Fonts
cask "font-jetbrains-mono"

# Mac App Store
mas "Slack", id: 803453959
mas "Paprika Recipe Manager 3", id: 1303222628
