# Ctrl-s prefix
set -g prefix C-s

# Reload config with <prefix> R
bind R source-file ~/.config/tmux/tmux.conf \; display "Reloaded tmux config"

# Remove "are you sure" prompt when killing panes
bind x kill-pane

# Mouse
set -g mouse on

# Extended keys
set -s extended-keys always
set -as terminal-overrides 'xterm-ghostty:extkeys'

# Scroll back
set -g history-limit 5000

# 1 based indexing
set -g base-index 1
set -g pane-base-index 1

# Update numbers
set -g renumber-windows on

# Focus events
set -g focus-events on

# True color support
#set -g default-terminal "${TERM}"
#set -sg terminal-overrides ",*:RGB"

# hjkl for pane navigation, hl can move between windows too
bind -r j select-pane -D
bind -r k select-pane -U
bind -r h select-pane -L
bind -r l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Alternate - cycle windows with h and l
# bind -r h if-shell '[ "#{pane_at_left}" -eq 1 ]' "previous-window" "select-pane -L"
# bind -r l if-shell '[ "#{pane_at_right}" -eq 1 ]' "next-window" "select-pane -R"

# zoom with <enter>
bind -r Enter resize-pane -Z

# - | to split vertically or horizontally
bind -r | split-window -h -c "#{pane_current_path}"
bind -r - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# t to open new window
bind t new-window -c "#{pane_current_path}"

# clear history (https://github.com/tristan-secord/dotfiles/blob/00d9f7ceea06ccd1f4515529897d0cb52411526f/tmux/tmux.conf#L45)
bind K send-keys -R ^M \; clear-history

# q to kill pane, Q to kill window
bind q kill-pane
bind Q kill-window

# g to display panes / jump to pane
bind g display-panes
set -g display-panes-time 2000

# r to rename
bind r command-prompt -I "#{window_name}" "rename-window '%%'"

# Style (https://www.youtube.com/watch?v=6Jgl5wphD00)
set -g @gray_light "#D8DEE9"
set -g @gray_medium "#ABB2BF"
set -g @gray_dark "#3B4252"
set -g @green_soft "#A3BE8C"
set -g @blue_muted "#81A1C1"
set -g @cyan_soft "#88C0D0"

# Borders
set -g pane-border-style "fg=#{@gray_dark}"
set -g pane-active-border-style "fg=#{@gray_medium}"

# Status bar
set -g status-position top
set -g status-left-length 100
set -g status-style "fg=#{@gray_light},bg=default"
set -g status-left " "
set -g status-right "#[fg=#{@green_soft},bold]#S"

set -g message-style 'fg=#{@green_soft} bg=default'

set -g mode-style "bg=#{@green_soft},fg=#{@gray_dark}"

# Name windows to index so "anonymous" windows can be identified below
set -g automatic-rename on
set -g automatic-rename-format "#{window_index}"

set -g window-status-format "#{?window_bell_flag,● ,  }#{?#{==:#{window_name},#{window_index}},#I,#I#[fg=colour244] #{window_name}#[default]}  "
set -g window-status-current-format "  #{?#{==:#{window_name},#{window_index}},#[underscore]#I#[nounderscore],#[underscore]#I#[nounderscore]#[fg=colour244] #{window_name}#[default]}  "

# Bell - any window
set -g bell-action any
set -g window-status-bell-style "none"

# Layouts:  <prefix> A <number>
bind A switch-client -T layouts
bind -T layouts 1 source-file ~/.config/tmux/layouts/23.conf

# Focus in/out - TODO: store per client?
if-shell -F '#{==:#{@client_focused},}' 'set -gq @client_focused 0'
set-hook -g client-focus-in  'set-option -gq @client_focused 1'
set-hook -g client-focus-out 'set-option -gq @client_focused 0'

# vim style search in copy mode
set -g wrap-search on
setw -g mode-keys vi
bind-key -T copy-mode-vi / command-prompt -i -p "/" "send -X search-forward-incremental '%%'"
bind-key -T copy-mode-vi ? command-prompt -i -p "?" "send -X search-backward-incremental '%%'"
